import { NAME } from './constants';

export const GET_SERVERS_REQUEST = `${NAME}.GET_SERVERS_REQUEST`;
export const GET_SERVERS_SUCCESS = `${NAME}.GET_SERVERS_SUCCESS`;
export const GET_SERVERS_FAILURE = `${NAME}.GET_SERVERS_FAILURE`;
